import React, { useState } from "react";
import {
  Card,
  CardContent,
  CardFooter,
  HeaderCard,
  TitleCard,
} from "../ui/card";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "../ui/select";
import { Button } from "../ui/button";
import {
  useEditEnquiryMutation,
  useGetAllEnquiriesQuery,
} from "@/redux/features/enquiries/enquiriesApi";
import toast from "react-hot-toast";
import ChangerExporter from "../ui/ChangerExporter";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * EnquiryPage Component
 * Displays detailed information about an enquiry and allows updating its status.
 *
 * @param {object} props - The props for the component.
 * @param {object} props.enquiry - The enquiry details.
 * @param {string} props.enquiry._id - The unique identifier for the enquiry.
 * @param {string} props.enquiry.name - The name of the customer.
 * @param {string} props.enquiry.email - The email of the customer.
 * @param {string} props.enquiry.mobile - The mobile number of the customer.
 * @param {string} props.enquiry.comment - The comment provided by the customer.
 * @param {string} props.enquiry.status - The current status of the enquiry.
 */
const EnquiryPage = ({ enquiry }: { enquiry: Props["enquiry"] }) => {
  const [status, setStatus] = useState(enquiry.status);
  const [editEnquiry, { isLoading }] = useEditEnquiryMutation();
  const { refetch } = useGetAllEnquiriesQuery(
    {},
    { refetchOnMountOrArgChange: true }
  );

  /**
   * Handles updating the status of the enquiry.
   */
  const handleUpdateStatus = async () => {
    try {
      const data = { status };
      await editEnquiry({ id: enquiry._id, data }).unwrap();
      toast.success("Enquiry status updated successfully!");
      refetch();
    } catch (error: any) {
      const errorMessage = error?.data?.message || "Failed to update status.";
      toast.error(errorMessage);
    }
  };

  /**
   * Handles exporting the enquiry details to a professionally designed PDF file.
   */
  const handleExportPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor("#333");
    doc.text("Enquiry Report", 105, 20, { align: "center" });

    // Add a horizontal line
    doc.setDrawColor(200, 200, 200);
    doc.line(10, 25, 200, 25);

    // Add enquiry details
    doc.setFontSize(14);
    doc.setTextColor("#555");
    doc.text("Customer Information", 14, 35);
    autoTable(doc, {
      startY: 40,
      head: [["Field", "Details"]],
      body: [
        ["Name", enquiry.name],
        ["Email", enquiry.email],
        ["Mobile", enquiry.mobile],
        ["Comment", enquiry.comment],
        ["Status", enquiry.status],
      ],
      styles: { fontSize: 12, textColor: "#333" },
      headStyles: { fillColor: [22, 160, 133], textColor: "#fff" },
      alternateRowStyles: { fillColor: [240, 240, 240] },
    });

    // Add footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor("#888");
    doc.text(
      "Generated by Dashboard E-commerce",
      105,
      pageHeight - 10,
      { align: "center" }
    );

    doc.save(`Enquiry_${enquiry._id}.pdf`);
  };

  const links = [
    { name: "Home", url: "/en" },
    { name: "Dashboard", url: "/en/dashboard" },
    { name: "Enquiries", url: "/en/dashboard/enquiries" },
  ];

  return (
    <section className="w-full">
      {/* Navigation and Export Options */}
      <ChangerExporter
        links={links}
        active="Enquiry Details"
        isPDF
        dataPDF={{ handleExportPDF }}
      />

      {/* Enquiry Information */}
      <div className="w-full mt-10 grid grid-cols-1 lg:grid-cols-2">
        <Card className="w-full bg-white dark:bg-black-100 shadow rounded-lg">
          <HeaderCard className="w-full p-5">
            <TitleCard
              title="Enquiry Information"
              className="text-xl font-semibold text-black dark:text-white"
            />
          </HeaderCard>
          <CardContent className="w-full p-5">
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-2">
                <span className="font-semibold text-gray-700 dark:text-white">
                  Name:
                </span>
                <span className="text-gray-900 dark:text-gray-300">
                  {enquiry.name}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-semibold text-gray-700 dark:text-white">
                  Email:
                </span>
                <span className="text-gray-900 dark:text-gray-300">
                  {enquiry.email}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-semibold text-gray-700 dark:text-white">
                  Mobile:
                </span>
                <span className="text-gray-900 dark:text-gray-300">
                  {enquiry.mobile}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-semibold text-gray-700 dark:text-white">
                  Comment:
                </span>
                <span className="text-gray-900 dark:text-gray-300">
                  {enquiry.comment}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-semibold text-gray-700 dark:text-white">
                  Status:
                </span>
                <span className="px-3 py-1 rounded-full text-sm font-semibold bg-blue-100 text-blue-800">
                  {enquiry.status}
                </span>
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex items-center justify-between p-5">
            <div className="w-max">
              <Select
                value={status}
                onValueChange={(value) => setStatus(value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent className="dark:bg-black-200">
                  <SelectItem value="Submitted">Submitted</SelectItem>
                  <SelectItem value="Contacted">Contacted</SelectItem>
                  <SelectItem value="In Progress">In Progress</SelectItem>
                  <SelectItem value="Resolved">Resolved</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button
              onClick={handleUpdateStatus}
              className="bg-blue-650 hover:bg-blue-600 dark:text-white"
              disabled={isLoading}
            >
              {isLoading ? "Updating..." : "Update"}
            </Button>
          </CardFooter>
        </Card>
      </div>
    </section>
  );
};

export default EnquiryPage;
